var repoVersion = "mainSceneNov26"
var repoLinkJsDeliver = "https://cdn.jsdelivr.net/gh/ghaithlab/jslibs@" + repoVersion + "/homeScreenSceneNov26/";
var repoLinkGH = "https://raw.githubusercontent.com/ghaithlab/jslibs/"+  repoVersion +"/homeScreenSceneNov26/";
var repoLinkCloudinary = "https://res.cloudinary.com/dafltya7l/image/upload/v1670090650/bakkoura-home-animation/";
var repoLink = repoLinkCloudinary;

var images = [
    "watch-main.webp",    
    "watch-main-1.webp",
    "watch-main-2.webp",
    "watch-main-3.webp",
    "watch-main-4.webp",
    "watch-main-5.webp",
    "watch-main-6.webp",
    "watch-main-7.webp",
    "watch-main-8.webp",
    "watch-main-9.webp",
    "watch-main-10.webp",
    "watch-main-11.webp",
    "watch-main-12.webp",
    "watch-main-13.webp",
    "watch-main-14.webp",
    "watch-main-15.webp",
    "watch-main-16.webp",
    "watch-main-17.webp",
    "watch-main-18.webp",
    "watch-main-19.webp",
    "watch-main-20.webp",
    "watch-main-21.webp",
    "watch-main-22.webp",
    "watch-main-23.webp",
    "watch-main-24.webp",
    "watch-main-25.webp",
    "watch-main-26.webp",
    "watch-main-27.webp",
    "watch-main-28.webp",
    "watch-main-29.webp",
    "watch-main-30.webp",
    "watch-main-31.webp",
    "watch-main-32.webp",
    "watch-main-33.webp",
    "watch-main-34.webp",
    "watch-main-35.webp",
    "watch-main-36.webp",
    "watch-main-37.webp",
    "watch-main-38.webp",
    "watch-main-39.webp",
    "watch-main-40.webp",
    "watch-main-41.webp",
    "watch-main-42.webp",
    "watch-main-43.webp",
    "watch-main-44.webp",
    "watch-main-45.webp",
    "watch-main-46.webp",
    "watch-main-47.webp",
    "watch-main-48.webp",
    "watch-main-49.webp",
    "watch-main-50.webp",
    "watch-main-51.webp",
    "watch-main-52.webp",
    "watch-main-53.webp",
    "watch-main-54.webp",
    "watch-main-55.webp",
    "watch-main-56.webp",
    "watch-main-57.webp",
    "watch-main-58.webp",
    "watch-main-59.webp",
    "watch-main-60.webp",
    "watch-main-61.webp",
    "watch-main-62.webp",
    "watch-main-63.webp",
    "watch-main-64.webp",
    "watch-main-65.webp",
    "watch-main-66.webp",
    "watch-main-67.webp",
    "watch-main-68.webp",
    "watch-main-69.webp",
    "watch-main-71.webp",
    "watch-main-72.webp",
    "watch-main-73.webp",
    "watch-main-74.webp",
    "watch-main-75.webp",
    "watch-main-76.webp",
    "watch-main-77.webp",
    "watch-main-78.webp",
    "watch-main-79.webp",
    "watch-main-80.webp",
    "watch-main-81.webp",
    "watch-main-82.webp",
    "watch-main-83.webp",
    "watch-main-84.webp",
    "watch-main-85.webp",
    "watch-main-86.webp",
    "watch-main-87.webp",
    "watch-main-88.webp",
    "watch-main-89.webp",
    "watch-main-90.webp",
    "watch-main-91.webp",
    "watch-main-92.webp",
    "watch-main-93.webp",
    "watch-main-94.webp",
    "watch-main-95.webp",
    "watch-main-96.webp",
    "watch-main-97.webp",
    "watch-main-98.webp",
    "watch-main-99.webp",
    "watch-main-100.webp",
    "watch-main-101.webp",
    "watch-main-102.webp",
    "watch-main-103.webp",
    "watch-main-104.webp",
    "watch-main-105.webp",
    "watch-main-106.webp",
    "watch-main-107.webp",
    "watch-main-108.webp",
    "watch-main-109.webp",
    "watch-main-110.webp",
    "watch-main-111.webp",
    "watch-main-112.webp",
    "watch-main-113.webp",
    "watch-main-114.webp",
    "watch-main-115.webp",
    "watch-main-116.webp",
    "watch-main-117.webp",
    "watch-main-118.webp",
    "watch-main-119.webp",
    "watch-main-120.webp",
    "watch-main-121.webp",
    "watch-main-122.webp",
    "watch-main-123.webp",
    "watch-main-124.webp",
    "watch-main-125.webp",
    "watch-main-126.webp",
    "watch-main-127.webp",
    "watch-main-128.webp",
    "watch-main-129.webp",
    "watch-main-130.webp",
    "watch-main-131.webp",
    "watch-main-132.webp",
    "watch-main-133.webp",
    "watch-main-134.webp",
    "watch-main-135.webp",
    "watch-main-136.webp",
    "watch-main-137.webp",
    "watch-main-138.webp",
    "watch-main-139.webp",
    "watch-main-140.webp",
    "watch-main-141.webp",
    "watch-main-142.webp",
    "watch-main-143.webp",
    "watch-main-144.webp",
    "watch-main-145.webp",
    "watch-main-146.webp",
    "watch-main-147.webp",
    "watch-main-148.webp",
    "watch-main-149.webp",
    "watch-main-150.webp",
    "watch-main-151.webp",
    "watch-main-152.webp",
    "watch-main-153.webp",
    "watch-main-154.webp",
    "watch-main-155.webp",
    "watch-main-156.webp",
    "watch-main-157.webp",
    "watch-main-158.webp",
    "watch-main-159.webp",
    "watch-main-160.webp",
    "watch-main-161.webp",
    "watch-main-162.webp",
    "watch-main-163.webp",
    "watch-main-164.webp",
    "watch-main-165.webp",
    "watch-main-166.webp",
    "watch-main-167.webp",
    "watch-main-168.webp",
    "watch-main-169.webp",
    "watch-main-171.webp",
    "watch-main-172.webp",
    "watch-main-173.webp",
    "watch-main-174.webp",
    "watch-main-175.webp",
    "watch-main-176.webp",
    "watch-main-177.webp",
    "watch-main-178.webp",
    "watch-main-179.webp",
    "watch-main-180.webp",
    "watch-main-181.webp",
    "watch-main-182.webp",
    "watch-main-183.webp",
    "watch-main-184.webp",
    "watch-main-185.webp",
    "watch-main-186.webp",
    "watch-main-187.webp",
    "watch-main-188.webp",
    "watch-main-189.webp",
    "watch-main-180.webp",
    "watch-main-191.webp",
    "watch-main-192.webp",
    "watch-main-193.webp",
    "watch-main-194.webp",
    "watch-main-195.webp",
    "watch-main-196.webp",
    "watch-main-197.webp",
    "watch-main-198.webp",
    "watch-main-199.webp",
    "watch-main-200.webp",
    "watch-main-201.webp",
    "watch-main-202.webp",
    "watch-main-203.webp",
    "watch-main-204.webp",
    "watch-main-205.webp",
    "watch-main-206.webp",
    "watch-main-207.webp",
    "watch-main-208.webp",
    "watch-main-209.webp",
    "watch-main-210.webp",
    "watch-main-211.webp",
    "watch-main-212.webp",
    "watch-main-213.webp",
    "watch-main-214.webp",
    "watch-main-215.webp",
    "watch-main-216.webp",
    "watch-main-217.webp",
    "watch-main-218.webp",
    "watch-main-219.webp",
    "watch-main-220.webp",
    "watch-main-221.webp",
    "watch-main-222.webp",
    "watch-main-223.webp",
    "watch-main-224.webp",
    "watch-main-225.webp",
    "watch-main-226.webp",
    "watch-main-227.webp",
    "watch-main-228.webp",
    "watch-main-229.webp",
    "watch-main-230.webp",
    "watch-main-231.webp",
    "watch-main-232.webp",
    "watch-main-233.webp",
    "watch-main-234.webp",];

var imgs = new Array()
                        
                            for (i = 0; i < images.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink + images[i];
                            }
                    var obj = {curImg: 0};
                    var tween = TweenMax.to(obj, 5,
                        {
                            curImg: images.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg").attr("src",repoLink + images[obj.curImg]); 
                            }
                        }
                    );
                    var controller = new ScrollMagic.Controller();
                    var scene = new ScrollMagic.Scene({triggerElement: "#trigger", duration: 3100})
                                    .setTween(tween)
                                    //.addIndicators()//
                                    .addTo(controller);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });
        //second section// 
    var images1 = [

    "watch-main-235.webp",
    "watch-main-236.webp",
    "watch-main-237.webp",
    "watch-main-238.webp",
    "watch-main-239.webp",
    "watch-main-240.webp",
    "watch-main-241.webp",
    "watch-main-242.webp",
    "watch-main-243.webp",
    "watch-main-244.webp",
    "watch-main-245.webp",
    "watch-main-246.webp",
    "watch-main-247.webp",
    "watch-main-248.webp",
    "watch-main-249.webp",
    "watch-main-250.webp",
    "watch-main-251.webp",
    "watch-main-252.webp",
    "watch-main-253.webp",
    "watch-main-254.webp",
    "watch-main-255.webp",
    "watch-main-256.webp",
    "watch-main-257.webp",
    "watch-main-258.webp",
    "watch-main-259.webp",
    "watch-main-260.webp",
    "watch-main-261.webp",
    "watch-main-262.webp",
    "watch-main-263.webp",
    "watch-main-264.webp",
    "watch-main-265.webp",
    "watch-main-266.webp",
    "watch-main-267.webp",
    "watch-main-268.webp",
    "watch-main-269.webp",
    "watch-main-271.webp",
    "watch-main-272.webp",
    "watch-main-273.webp",
    "watch-main-274.webp",
    "watch-main-275.webp",
    "watch-main-276.webp",
    "watch-main-277.webp",
    "watch-main-278.webp",
    "watch-main-279.webp",
    "watch-main-280.webp",
    "watch-main-281.webp",
    "watch-main-282.webp",
    "watch-main-283.webp",
    "watch-main-284.webp",
    "watch-main-285.webp",
    "watch-main-286.webp",
    "watch-main-287.webp",
    "watch-main-288.webp",
    "watch-main-289.webp"];

imgs = new Array()
                        
                            for (i = 0; i < images1.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink + images1[i];
                            }
                    var obj1 = {curImg: 0};
                    var tween1 = TweenMax.to(obj1, 5,
                        {
                            curImg: images1.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg1").attr("src",repoLink + images1[obj1.curImg]);
                            }
                        }
                    );
                    var controller1 = new ScrollMagic.Controller();
                    var scene1 = new ScrollMagic.Scene({triggerElement: "#trigger1", duration: 2600})
                                    .setTween(tween1)
                                    //.addIndicators()// 
                                    .addTo(controller1);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });

// third section
    var images2 = [

    "watch-main-290.webp",
    "watch-main-291.webp",
    "watch-main-292.webp",
    "watch-main-293.webp",
    "watch-main-294.webp",
    "watch-main-295.webp",
    "watch-main-296.webp",
    "watch-main-297.webp",
    "watch-main-299.webp",
    "watch-main-300.webp",
    "watch-main-301.webp",
    "watch-main-302.webp",
    "watch-main-303.webp",
    "watch-main-304.webp",
    "watch-main-305.webp",
    "watch-main-306.webp",
    "watch-main-307.webp",
    "watch-main-308.webp",
    "watch-main-309.webp",
    "watch-main-310.webp",
    "watch-main-311.webp",
    "watch-main-312.webp",
    "watch-main-313.webp",
    "watch-main-314.webp",
    "watch-main-315.webp",
    "watch-main-316.webp",
    "watch-main-317.webp",
    "watch-main-318.webp",
    "watch-main-319.webp",
    "watch-main-320.webp",
    "watch-main-321.webp",
    "watch-main-322.webp",
    "watch-main-323.webp",
    "watch-main-324.webp",
    "watch-main-325.webp",
    "watch-main-326.webp",
    "watch-main-327.webp",
    "watch-main-328.webp",
    "watch-main-329.webp",
    "watch-main-330.webp",
    "watch-main-331.webp",
    "watch-main-332.webp",
    "watch-main-333.webp",
    "watch-main-334.webp",
    "watch-main-335.webp",
    "watch-main-336.webp",
    "watch-main-337.webp",
    "watch-main-338.webp",
    "watch-main-339.webp",
    "watch-main-340.webp",
    "watch-main-341.webp",
    "watch-main-342.webp",
    "watch-main-343.webp",
    "watch-main-344.webp",
    "watch-main-345.webp",
    "watch-main-346.webp",
    "watch-main-347.webp",
    "watch-main-348.webp",
    "watch-main-349.webp",
    "watch-main-350.webp",
    "watch-main-351.webp",
    "watch-main-352.webp",
    "watch-main-353.webp",
    "watch-main-354.webp",
    "watch-main-355.webp",
    "watch-main-356.webp",
    "watch-main-357.webp",
    "watch-main-358.webp",
    "watch-main-359.webp",
    "watch-main-360.webp",
    "watch-main-361.webp",
    "watch-main-362.webp",
    "watch-main-363.webp",
    "watch-main-364.webp",
    "watch-main-365.webp",
    "watch-main-366.webp",
    "watch-main-367.webp",
    "watch-main-368.webp",
    "watch-main-369.webp",
    "watch-main-371.webp",
    "watch-main-372.webp",
    "watch-main-373.webp",
    "watch-main-374.webp",
    "watch-main-375.webp",
    "watch-main-376.webp",
    "watch-main-377.webp",
    "watch-main-378.webp",
    "watch-main-379.webp",
    "watch-main-380.webp",
    "watch-main-381.webp",
    "watch-main-382.webp",
    "watch-main-383.webp",
    "watch-main-384.webp",
    "watch-main-385.webp",
    "watch-main-386.webp",
    "watch-main-387.webp",
    "watch-main-388.webp",
    "watch-main-389.webp",
    "watch-main-390.webp",
    "watch-main-391.webp",
    "watch-main-392.webp",
    "watch-main-393.webp",
    "watch-main-394.webp",
    "watch-main-395.webp",
    "watch-main-396.webp",
    "watch-main-397.webp"];

imgs = new Array()
                        
                            for (i = 0; i < images2.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink+ images2[i];
                            }
                    var obj2 = {curImg: 0};
                    var tween2 = TweenMax.to(obj2, 5,
                        {
                            curImg: images2.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg2").attr("src",repoLink + images2[obj2.curImg]);
                            }
                        }
                    );
                    var controller2 = new ScrollMagic.Controller();
                    var scene2 = new ScrollMagic.Scene({triggerElement: "#trigger2", duration: 1800})
                                    .setTween(tween2)
                                    //.addIndicators()// 
                                    .addTo(controller2);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });
    
    //fourth section
    var images3 = [
      
    "e-watch-main.webp",    
    "e-watch-main-1.webp",
    "e-watch-main-2.webp",
    "e-watch-main-3.webp",
    "e-watch-main-4.webp",
    "e-watch-main-5.webp",
    "e-watch-main-6.webp",
    "e-watch-main-7.webp",
    "e-watch-main-8.webp",
    "e-watch-main-9.webp",
    "e-watch-main-10.webp",
    "e-watch-main-11.webp",
    "e-watch-main-12.webp",
    "e-watch-main-13.webp",
    "e-watch-main-14.webp",
    "e-watch-main-15.webp",
    "e-watch-main-16.webp",
    "e-watch-main-17.webp",
    "e-watch-main-18.webp",
    "e-watch-main-19.webp",
    "e-watch-main-20.webp",
    "e-watch-main-21.webp",
    "e-watch-main-22.webp",
    "e-watch-main-23.webp",
    "e-watch-main-24.webp",
    "e-watch-main-25.webp",
    "e-watch-main-26.webp",
    "e-watch-main-27.webp",
    "e-watch-main-28.webp",
    "e-watch-main-29.webp",
    "e-watch-main-30.webp",
    "e-watch-main-31.webp",
    "e-watch-main-32.webp",
    "e-watch-main-33.webp",
    "e-watch-main-34.webp",
    "e-watch-main-35.webp",
    "e-watch-main-36.webp",
    "e-watch-main-37.webp",
    "e-watch-main-38.webp",
    "e-watch-main-39.webp",
    "e-watch-main-40.webp",
    "e-watch-main-41.webp",
    "e-watch-main-42.webp",
    "e-watch-main-43.webp",
    "e-watch-main-44.webp",
    "e-watch-main-45.webp",
    "e-watch-main-46.webp",
    "e-watch-main-47.webp",
    "e-watch-main-48.webp",
    "e-watch-main-49.webp",
    "e-watch-main-50.webp",
    "e-watch-main-51.webp",
    "e-watch-main-52.webp",
    "e-watch-main-53.webp",
    "e-watch-main-54.webp",
    "e-watch-main-55.webp",
    "e-watch-main-56.webp",
    "e-watch-main-57.webp",
    "e-watch-main-58.webp",
    "e-watch-main-59.webp",
    "e-watch-main-60.webp",
    "e-watch-main-61.webp",
    "e-watch-main-62.webp",
    "e-watch-main-63.webp",
    "e-watch-main-64.webp",
    "e-watch-main-65.webp",
    "e-watch-main-66.webp",
    "e-watch-main-67.webp",
    "e-watch-main-68.webp",
    "e-watch-main-69.webp",
    "e-watch-main-71.webp",
    "e-watch-main-72.webp",
    "e-watch-main-73.webp",
    "e-watch-main-74.webp",
    "e-watch-main-75.webp",
    "e-watch-main-76.webp",
    "e-watch-main-77.webp",
    "e-watch-main-78.webp",
    "e-watch-main-79.webp",
    "e-watch-main-80.webp",
    "e-watch-main-81.webp",
    "e-watch-main-82.webp",
    "e-watch-main-83.webp",
    "e-watch-main-84.webp",
    "e-watch-main-85.webp",
    "e-watch-main-86.webp",
    "e-watch-main-87.webp",
    "e-watch-main-88.webp",
    "e-watch-main-89.webp",
    "e-watch-main-90.webp",
    "e-watch-main-91.webp",
    "e-watch-main-92.webp",
    "e-watch-main-93.webp",
    "e-watch-main-94.webp",
    "e-watch-main-95.webp",
    "e-watch-main-96.webp",
    "e-watch-main-97.webp",
    "e-watch-main-98.webp",
    "e-watch-main-99.webp",
    "e-watch-main-100.webp",
    "e-watch-main-101.webp",
    "e-watch-main-102.webp",
    "e-watch-main-103.webp",
    "e-watch-main-104.webp",
    "e-watch-main-105.webp",
    "e-watch-main-106.webp",
    "e-watch-main-107.webp",
    "e-watch-main-108.webp",
    "e-watch-main-109.webp",
    "e-watch-main-110.webp",
    "e-watch-main-111.webp",
    "e-watch-main-112.webp",
    "e-watch-main-113.webp",
    "e-watch-main-114.webp",
    "e-watch-main-115.webp",
    "e-watch-main-116.webp",
    "e-watch-main-117.webp",
    "e-watch-main-118.webp",
    "e-watch-main-119.webp",
    "e-watch-main-120.webp",
    "e-watch-main-121.webp",
    "e-watch-main-122.webp",
    "e-watch-main-123.webp",
    "e-watch-main-124.webp",
    "e-watch-main-125.webp",
    "e-watch-main-126.webp",
    "e-watch-main-127.webp",
    "e-watch-main-128.webp",
    "e-watch-main-129.webp",
    "e-watch-main-130.webp",
    "e-watch-main-131.webp",
    "e-watch-main-132.webp",
    "e-watch-main-133.webp",
    "e-watch-main-134.webp",
    "e-watch-main-135.webp",
    "e-watch-main-136.webp",
    "e-watch-main-137.webp",
    "e-watch-main-138.webp",
    "e-watch-main-139.webp",
    "e-watch-main-140.webp",
    "e-watch-main-141.webp",
    "e-watch-main-142.webp",
    "e-watch-main-143.webp",
    "e-watch-main-144.webp",
    "e-watch-main-145.webp",
    "e-watch-main-146.webp",
    "e-watch-main-147.webp",
    "e-watch-main-148.webp",
    "e-watch-main-149.webp",
    "e-watch-main-150.webp",
    "e-watch-main-151.webp",
    "e-watch-main-152.webp",
    "e-watch-main-153.webp",
    "e-watch-main-154.webp",
    "e-watch-main-155.webp",
    "e-watch-main-156.webp",
    "e-watch-main-157.webp",
    "e-watch-main-158.webp",
    "e-watch-main-159.webp",
    "e-watch-main-160.webp",
    "e-watch-main-161.webp",
    "e-watch-main-162.webp",
    "e-watch-main-163.webp",
    "e-watch-main-164.webp",
    "e-watch-main-165.webp",
    "e-watch-main-166.webp",
    "e-watch-main-167.webp",
    "e-watch-main-168.webp",
    "e-watch-main-169.webp",
    "e-watch-main-171.webp",
    "e-watch-main-172.webp",];

imgs = new Array()
                        
                    for (i = 0; i < images3.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink + images3[i];
                            }
                    var obj3 = {curImg: 0};
                    var tween3 = TweenMax.to(obj3, 5,
                        {
                            curImg: images3.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg3").attr("src",repoLink + images3[obj3.curImg]);
                            }
                        }
                    );
                    var controller3 = new ScrollMagic.Controller();
                    var scene3 = new ScrollMagic.Scene({triggerElement: "#trigger3", duration: 1100})
                                    .setTween(tween3)
                                    //.addIndicators() //
                                    .addTo(controller3);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });
