var repoVersion = "mainSceneNov22"
var repoLinkJsDeliver = "https://cdn.jsdelivr.net/gh/ghaithlab/jslibs@" + repoVersion + "/homeScreenSceneNov26/";
var repoLinkGH = "https://raw.githubusercontent.com/ghaithlab/jslibs/"+  repoVersion +"/homeScreenSceneNov26/";
var repoLink = repoLinkGH;


var images = [
    "watch main000.webp",
    "watch main001.webp",
    "watch main002.webp",
    "watch main003.webp",
    "watch main004.webp",
    "watch main005.webp",
    "watch main006.webp",
    "watch main007.webp",
    "watch main008.webp",
    "watch main009.webp",
    "watch main010.webp",
    "watch main011.webp",
    "watch main012.webp",
    "watch main013.webp",
    "watch main014.webp",
    "watch main015.webp",
    "watch main016.webp",
    "watch main017.webp",
    "watch main018.webp",
    "watch main019.webp",
    "watch main020.webp",
    "watch main021.webp",
    "watch main022.webp",
    "watch main023.webp",
    "watch main024.webp",
    "watch main025.webp",
    "watch main026.webp",
    "watch main027.webp",
    "watch main028.webp",
    "watch main029.webp",
    "watch main030.webp",
    "watch main031.webp",
    "watch main032.webp",
    "watch main033.webp",
    "watch main034.webp",
    "watch main035.webp",
    "watch main036.webp",
    "watch main037.webp",
    "watch main038.webp",
    "watch main039.webp",
    "watch main040.webp",
    "watch main041.webp",
    "watch main042.webp",
    "watch main043.webp",
    "watch main044.webp",
    "watch main045.webp",
    "watch main046.webp",
    "watch main047.webp",
    "watch main048.webp",
    "watch main049.webp",
    "watch main050.webp",
    "watch main051.webp",
    "watch main052.webp",
    "watch main053.webp",
    "watch main054.webp",
    "watch main055.webp",
    "watch main056.webp",
    "watch main057.webp",
    "watch main058.webp",
    "watch main059.webp",
    "watch main060.webp",
    "watch main061.webp",
    "watch main062.webp",
    "watch main063.webp",
    "watch main064.webp",
    "watch main065.webp",
    "watch main066.webp",
    "watch main067.webp",
    "watch main068.webp",
    "watch main069.webp",
    "watch main071.webp",
    "watch main072.webp",
    "watch main073.webp",
    "watch main074.webp",
    "watch main075.webp",
    "watch main076.webp",
    "watch main077.webp",
    "watch main078.webp",
    "watch main079.webp",
    "watch main080.webp",
    "watch main081.webp",
    "watch main082.webp",
    "watch main083.webp",
    "watch main084.webp",
    "watch main085.webp",
    "watch main086.webp",
    "watch main087.webp",
    "watch main088.webp",
    "watch main089.webp",
    "watch main090.webp",
    "watch main091.webp",
    "watch main092.webp",
    "watch main093.webp",
    "watch main094.webp",
    "watch main095.webp",
    "watch main096.webp",
    "watch main097.webp",
    "watch main098.webp",
    "watch main099.webp",
    "watch main100.webp",
    "watch main101.webp",
    "watch main102.webp",
    "watch main103.webp",
    "watch main104.webp",
    "watch main105.webp",
    "watch main106.webp",
    "watch main107.webp",
    "watch main108.webp",
    "watch main109.webp",
    "watch main110.webp",
    "watch main111.webp",
    "watch main112.webp",
    "watch main113.webp",
    "watch main114.webp",
    "watch main115.webp",
    "watch main116.webp",
    "watch main117.webp",
    "watch main118.webp",
    "watch main119.webp",
    "watch main120.webp",
    "watch main121.webp",
    "watch main122.webp",
    "watch main123.webp",
    "watch main124.webp",
    "watch main125.webp",
    "watch main126.webp",
    "watch main127.webp",
    "watch main128.webp",
    "watch main129.webp",
    "watch main130.webp",
    "watch main131.webp",
    "watch main132.webp",
    "watch main133.webp",
    "watch main134.webp",
    "watch main135.webp",
    "watch main136.webp",
    "watch main137.webp",
    "watch main138.webp",
    "watch main139.webp",
    "watch main140.webp",
    "watch main141.webp",
    "watch main142.webp",
    "watch main143.webp",
    "watch main144.webp",
    "watch main145.webp",
    "watch main146.webp",
    "watch main147.webp",
    "watch main148.webp",
    "watch main149.webp",
    "watch main150.webp",
    "watch main151.webp",
    "watch main152.webp",
    "watch main153.webp",
    "watch main154.webp",
    "watch main155.webp",
    "watch main156.webp",
    "watch main157.webp",
    "watch main158.webp",
    "watch main159.webp",
    "watch main160.webp",
    "watch main161.webp",
    "watch main162.webp",
    "watch main163.webp",
    "watch main164.webp",
    "watch main165.webp",
    "watch main166.webp",
    "watch main167.webp",
    "watch main168.webp",
    "watch main169.webp",
    "watch main171.webp",
    "watch main172.webp",
    "watch main173.webp",
    "watch main174.webp",
    "watch main175.webp",
    "watch main176.webp",
    "watch main177.webp",
    "watch main178.webp",
    "watch main179.webp",
    "watch main180.webp",
    "watch main181.webp",
    "watch main182.webp",
    "watch main183.webp",
    "watch main184.webp",
    "watch main185.webp",
    "watch main186.webp",
    "watch main187.webp",
    "watch main188.webp",
    "watch main189.webp",
    "watch main180.webp",
    "watch main191.webp",
    "watch main192.webp",
    "watch main193.webp",
    "watch main194.webp",
    "watch main195.webp",
    "watch main196.webp",
    "watch main197.webp",
    "watch main198.webp",
    "watch main199.webp",
    "watch main200.webp",
    "watch main201.webp",
    "watch main202.webp",
    "watch main203.webp",
    "watch main204.webp",
    "watch main205.webp",
    "watch main206.webp",
    "watch main207.webp",
    "watch main208.webp",
    "watch main209.webp",
    "watch main210.webp",
    "watch main211.webp",
    "watch main212.webp",
    "watch main213.webp",
    "watch main214.webp",
    "watch main215.webp",
    "watch main216.webp",
    "watch main217.webp",
    "watch main218.webp",
    "watch main219.webp",
    "watch main220.webp",
    "watch main221.webp",
    "watch main222.webp",
    "watch main223.webp",
    "watch main224.webp",
    "watch main225.webp",
    "watch main226.webp",
    "watch main227.webp",
    "watch main228.webp",
    "watch main229.webp",
    "watch main230.webp",
    "watch main231.webp",
    "watch main232.webp",
    "watch main233.webp",
    "watch main234.webp",];

var imgs = new Array()
                        
                            for (i = 0; i < images.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink + images[i];
                            }
                    var obj = {curImg: 0};
                    var tween = TweenMax.to(obj, 5,
                        {
                            curImg: images.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg").attr("src",repoLink + images[obj.curImg]); 
                            }
                        }
                    );
                    var controller = new ScrollMagic.Controller();
                    var scene = new ScrollMagic.Scene({triggerElement: "#trigger", duration: 3100})
                                    .setTween(tween)
                                    //.addIndicators()//
                                    .addTo(controller);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });
        //second section// 
    var images1 = [

    "watch main235.webp",
    "watch main236.webp",
    "watch main237.webp",
    "watch main238.webp",
    "watch main239.webp",
    "watch main240.webp",
    "watch main241.webp",
    "watch main242.webp",
    "watch main243.webp",
    "watch main244.webp",
    "watch main245.webp",
    "watch main246.webp",
    "watch main247.webp",
    "watch main248.webp",
    "watch main249.webp",
    "watch main250.webp",
    "watch main251.webp",
    "watch main252.webp",
    "watch main253.webp",
    "watch main254.webp",
    "watch main255.webp",
    "watch main256.webp",
    "watch main257.webp",
    "watch main258.webp",
    "watch main259.webp",
    "watch main260.webp",
    "watch main261.webp",
    "watch main262.webp",
    "watch main263.webp",
    "watch main264.webp",
    "watch main265.webp",
    "watch main266.webp",
    "watch main267.webp",
    "watch main268.webp",
    "watch main269.webp",
    "watch main271.webp",
    "watch main272.webp",
    "watch main273.webp",
    "watch main274.webp",
    "watch main275.webp",
    "watch main276.webp",
    "watch main277.webp",
    "watch main278.webp",
    "watch main279.webp",
    "watch main280.webp",
    "watch main281.webp",
    "watch main282.webp",
    "watch main283.webp",
    "watch main284.webp",
    "watch main285.webp",
    "watch main286.webp",
    "watch main287.webp",
    "watch main288.webp",
    "watch main289.webp"];

imgs = new Array()
                        
                            for (i = 0; i < images1.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink + images1[i];
                            }
                    var obj1 = {curImg: 0};
                    var tween1 = TweenMax.to(obj1, 5,
                        {
                            curImg: images1.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg1").attr("src",repoLink + images1[obj1.curImg]);
                            }
                        }
                    );
                    var controller1 = new ScrollMagic.Controller();
                    var scene1 = new ScrollMagic.Scene({triggerElement: "#trigger1", duration: 2600})
                                    .setTween(tween1)
                                    //.addIndicators()// 
                                    .addTo(controller1);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });

// third section
    var images2 = [
    
    "watch main290.webp",
    "watch main291.webp",
    "watch main292.webp",
    "watch main293.webp",
    "watch main294.webp",
    "watch main295.webp",
    "watch main296.webp",
    "watch main297.webp",
    "watch main299.webp",
    "watch main300.webp",
    "watch main301.webp",
    "watch main302.webp",
    "watch main303.webp",
    "watch main304.webp",
    "watch main305.webp",
    "watch main306.webp",
    "watch main307.webp",
    "watch main308.webp",
    "watch main309.webp",
    "watch main310.webp",
    "watch main311.webp",
    "watch main312.webp",
    "watch main313.webp",
    "watch main314.webp",
    "watch main315.webp",
    "watch main316.webp",
    "watch main317.webp",
    "watch main318.webp",
    "watch main319.webp",
    "watch main320.webp",
    "watch main321.webp",
    "watch main322.webp",
    "watch main323.webp",
    "watch main324.webp",
    "watch main325.webp",
    "watch main326.webp",
    "watch main327.webp",
    "watch main328.webp",
    "watch main329.webp",
    "watch main330.webp",
    "watch main331.webp",
    "watch main332.webp",
    "watch main333.webp",
    "watch main334.webp",
    "watch main335.webp",
    "watch main336.webp",
    "watch main337.webp",
    "watch main338.webp",
    "watch main339.webp",
    "watch main340.webp",
    "watch main341.webp",
    "watch main342.webp",
    "watch main343.webp",
    "watch main344.webp",
    "watch main345.webp",
    "watch main346.webp",
    "watch main347.webp",
    "watch main348.webp",
    "watch main349.webp",
    "watch main350.webp",
    "watch main351.webp",
    "watch main352.webp",
    "watch main353.webp",
    "watch main354.webp",
    "watch main355.webp",
    "watch main356.webp",
    "watch main357.webp",
    "watch main358.webp",
    "watch main359.webp",
    "watch main360.webp",
    "watch main361.webp",
    "watch main362.webp",
    "watch main363.webp",
    "watch main364.webp",
    "watch main365.webp",
    "watch main366.webp",
    "watch main367.webp",
    "watch main368.webp",
    "watch main369.webp",
    "watch main371.webp",
    "watch main372.webp",
    "watch main373.webp",
    "watch main374.webp",
    "watch main375.webp",
    "watch main376.webp",
    "watch main377.webp",
    "watch main378.webp",
    "watch main379.webp",
    "watch main380.webp",
    "watch main381.webp",
    "watch main382.webp",
    "watch main383.webp",
    "watch main384.webp",
    "watch main385.webp",
    "watch main386.webp",
    "watch main387.webp",
    "watch main388.webp",
    "watch main389.webp",
    "watch main390.webp",
    "watch main391.webp",
    "watch main392.webp",
    "watch main393.webp",
    "watch main394.webp",
    "watch main395.webp",
    "watch main396.webp",
    "watch main397.webp"];

imgs = new Array()
                        
                            for (i = 0; i < images2.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink+ images2[i];
                            }
                    var obj2 = {curImg: 0};
                    var tween2 = TweenMax.to(obj2, 5,
                        {
                            curImg: images2.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg2").attr("src",repoLink + images2[obj2.curImg]);
                            }
                        }
                    );
                    var controller2 = new ScrollMagic.Controller();
                    var scene2 = new ScrollMagic.Scene({triggerElement: "#trigger2", duration: 1800})
                                    .setTween(tween2)
                                    //.addIndicators()// 
                                    .addTo(controller2);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });
    
    //fourth section
    var images3 = [
      
    "e-watch main000.webp",
    "e-watch main001.webp",
    "e-watch main002.webp",
    "e-watch main003.webp",
    "e-watch main004.webp",
    "e-watch main005.webp",
    "e-watch main006.webp",
    "e-watch main007.webp",
    "e-watch main008.webp",
    "e-watch main009.webp",
    "e-watch main010.webp",
    "e-watch main011.webp",
    "e-watch main012.webp",
    "e-watch main013.webp",
    "e-watch main014.webp",
    "e-watch main015.webp",
    "e-watch main016.webp",
    "e-watch main017.webp",
    "e-watch main018.webp",
    "e-watch main019.webp",
    "e-watch main020.webp",
    "e-watch main021.webp",
    "e-watch main022.webp",
    "e-watch main023.webp",
    "e-watch main024.webp",
    "e-watch main025.webp",
    "e-watch main026.webp",
    "e-watch main027.webp",
    "e-watch main028.webp",
    "e-watch main029.webp",
    "e-watch main030.webp",
    "e-watch main031.webp",
    "e-watch main032.webp",
    "e-watch main033.webp",
    "e-watch main034.webp",
    "e-watch main035.webp",
    "e-watch main036.webp",
    "e-watch main037.webp",
    "e-watch main038.webp",
    "e-watch main039.webp",
    "e-watch main040.webp",
    "e-watch main041.webp",
    "e-watch main042.webp",
    "e-watch main043.webp",
    "e-watch main044.webp",
    "e-watch main045.webp",
    "e-watch main046.webp",
    "e-watch main047.webp",
    "e-watch main048.webp",
    "e-watch main049.webp",
    "e-watch main050.webp",
    "e-watch main051.webp",
    "e-watch main052.webp",
    "e-watch main053.webp",
    "e-watch main054.webp",
    "e-watch main055.webp",
    "e-watch main056.webp",
    "e-watch main057.webp",
    "e-watch main058.webp",
    "e-watch main059.webp",
    "e-watch main060.webp",
    "e-watch main061.webp",
    "e-watch main062.webp",
    "e-watch main063.webp",
    "e-watch main064.webp",
    "e-watch main065.webp",
    "e-watch main066.webp",
    "e-watch main067.webp",
    "e-watch main068.webp",
    "e-watch main069.webp",
    "e-watch main071.webp",
    "e-watch main072.webp",
    "e-watch main073.webp",
    "e-watch main074.webp",
    "e-watch main075.webp",
    "e-watch main076.webp",
    "e-watch main077.webp",
    "e-watch main078.webp",
    "e-watch main079.webp",
    "e-watch main080.webp",
    "e-watch main081.webp",
    "e-watch main082.webp",
    "e-watch main083.webp",
    "e-watch main084.webp",
    "e-watch main085.webp",
    "e-watch main086.webp",
    "e-watch main087.webp",
    "e-watch main088.webp",
    "e-watch main089.webp",
    "e-watch main090.webp",
    "e-watch main091.webp",
    "e-watch main092.webp",
    "e-watch main093.webp",
    "e-watch main094.webp",
    "e-watch main095.webp",
    "e-watch main096.webp",
    "e-watch main097.webp",
    "e-watch main098.webp",
    "e-watch main099.webp",
    "e-watch main100.webp",
    "e-watch main101.webp",
    "e-watch main102.webp",
    "e-watch main103.webp",
    "e-watch main104.webp",
    "e-watch main105.webp",
    "e-watch main106.webp",
    "e-watch main107.webp",
    "e-watch main108.webp",
    "e-watch main109.webp",
    "e-watch main110.webp",
    "e-watch main111.webp",
    "e-watch main112.webp",
    "e-watch main113.webp",
    "e-watch main114.webp",
    "e-watch main115.webp",
    "e-watch main116.webp",
    "e-watch main117.webp",
    "e-watch main118.webp",
    "e-watch main119.webp",
    "e-watch main120.webp",
    "e-watch main121.webp",
    "e-watch main122.webp",
    "e-watch main123.webp",
    "e-watch main124.webp",
    "e-watch main125.webp",
    "e-watch main126.webp",
    "e-watch main127.webp",
    "e-watch main128.webp",
    "e-watch main129.webp",
    "e-watch main130.webp",
    "e-watch main131.webp",
    "e-watch main132.webp",
    "e-watch main133.webp",
    "e-watch main134.webp",
    "e-watch main135.webp",
    "e-watch main136.webp",
    "e-watch main137.webp",
    "e-watch main138.webp",
    "e-watch main139.webp",
    "e-watch main140.webp",
    "e-watch main141.webp",
    "e-watch main142.webp",
    "e-watch main143.webp",
    "e-watch main144.webp",
    "e-watch main145.webp",
    "e-watch main146.webp",
    "e-watch main147.webp",
    "e-watch main148.webp",
    "e-watch main149.webp",
    "e-watch main150.webp",
    "e-watch main151.webp",
    "e-watch main152.webp",
    "e-watch main153.webp",
    "e-watch main154.webp",
    "e-watch main155.webp",
    "e-watch main156.webp",
    "e-watch main157.webp",
    "e-watch main158.webp",
    "e-watch main159.webp",
    "e-watch main160.webp",
    "e-watch main161.webp",
    "e-watch main162.webp",
    "e-watch main163.webp",
    "e-watch main164.webp",
    "e-watch main165.webp",
    "e-watch main166.webp",
    "e-watch main167.webp",
    "e-watch main168.webp",
    "e-watch main169.webp",
    "e-watch main171.webp"];

imgs = new Array()
                        
                    for (i = 0; i < images3.length; i++) {
                                imgs[i] = new Image()
                                imgs[i].src = repoLink + images3[i];
                            }
                    var obj3 = {curImg: 0};
                    var tween3 = TweenMax.to(obj3, 5,
                        {
                            curImg: images3.length - 1,	
                            roundProps: "curImg",				
                            repeat: 0,									
                            immediateRender: true,			
                            ease: Linear.easeNone,			
                            onUpdate: function () {
                              $("#myimg3").attr("src",repoLink + images3[obj3.curImg]);
                            }
                        }
                    );
                    var controller3 = new ScrollMagic.Controller();
                    var scene3 = new ScrollMagic.Scene({triggerElement: "#trigger3", duration: 1100})
                                    .setTween(tween3)
                                    //.addIndicators() //
                                    .addTo(controller3);
                    $("form.move input[name=duration]:radio").change(function () {
                        scene.duration($(this).val());
                    });
